consumption_data <- read.csv("consumption_data.csv")
consumption_data$datetime <- as.POSIXct(paste(consumption_data$Date,consumption_data$Time),format= "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(consumption_data$datetime,consumption_data$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
plot(consumption_data$datetime,consumption_data$Voltage,type="l",ylab="Voltage",xlab="datetime")
plot(consumption_data$datetime,consumption_data$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="",col="Black")
lines(consumption_data$datetime,consumption_data$Sub_metering_2,type="l",col="Red")
lines(consumption_data$datetime,consumption_data$Sub_metering_3,type="l",col="Blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("Black","Red","Blue"),cex=0.40,lty=1,lwd=0.5,bty="n")
plot(consumption_data$datetime,consumption_data$Global_reactive_power,type="l",ylab="Global Reactive Power (kilowatts)",xlab="datetime")
